# Generated by Django 4.0.2 on 2022-02-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityweather',
            name='city_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
